apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-2lyq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0036-tenant/tkrw-pr712-0075-0036-app/devfile-sample-2lyq@sha256:1fdf2f1b69f8f6549771ab1da1a857707880b0905affc157ef0f08d2a94d1eca
        name: my-nodejs
        resources: {}
status: {}
